apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: "prod is king"
  sourceRepos:
    - "https://github.com/Kris-UlpiaTech/source-project.git"
  destinationServiceAccounts:
    - defaultServiceAccount: source-project-sa
      namespace: source-project
      server: https://kubernetes.default.svc
  destinations:
    - namespace: source-project
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
