# Example Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: snowflake-sql-secrets
  namespace: snowflake-sql
  annotations:
    kubernetes.io/service-account.name: "default"
type: Opaque
stringData:
  snowflakeAccount: "fd28786.eu-central-1"
  snowflakePassword: "9aY2cMFe4u!on!"
  snowflakeUsername: "KRIS"