apiVersion: batch/v1
kind: Job
metadata:
  name: snowflake-sql
  namespace: snowflake-sql
spec:
  template:
    metadata:
      labels:
        job: snowflake-sql
    spec:
      containers:
      - image: krizzon/snowsql-call:latest
        name: snowsql-call
        command: ["python", "main.py", "--config-file", "/tmp/config.txt", "--secret-file", "/tmp/secrets.txt"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/config.txt
          subPath: config.txt
        - name: secret-volume
          mountPath: /tmp/secrets.txt
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: snowflake-sql-config
      - name: secret-volume
        secret:
          secretName: snowflake-sql-secrets
